### ISSUE TITLE
How i get pre-trained weights?

### ISSUE THREAD

**Issue by faisalshahbaz** [ShantamShorewala/vehicle-speed-estimation#1]
Hi Shantam,

I using your repo, it is very impressive code implementation. I am stuck in deepsort class. Line 26

self.encoder = vehicle_encoder('weights/vehicle_vgg.h5')

How i get vehicle_vgg.h5 weight file.

**Comment by ShantamShorewala** [comment]
Our work on this is actually due to be published soon. We will be releasing the dataset as well as the reproducible code soon after.
